require('dotenv').config();
const express=require('express');
const Database=require('better-sqlite3');
const OpenAI=require('openai');
const path=require('path');
const app=express();
const PORT=process.env.PORT||3000;
const db=new Database(process.env.DB_PATH||'trading-journal.db');
db.pragma('journal_mode = WAL');
db.exec(`CREATE TABLE IF NOT EXISTS trades(id INTEGER PRIMARY KEY AUTOINCREMENT,date TEXT NOT NULL,symbol TEXT NOT NULL,direction TEXT NOT NULL CHECK(direction IN ('Long','Short')),setup TEXT NOT NULL,entry REAL NOT NULL,exit REAL NOT NULL,quantity REAL NOT NULL,risk REAL DEFAULT 0,emotion TEXT,notes TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP)`);
const calc=t=>({...t,pnl:(t.direction==='Long'?(t.exit-t.entry):(t.entry-t.exit))*t.quantity,rMultiple:t.risk?((t.direction==='Long'?(t.exit-t.entry):(t.entry-t.exit))*t.quantity)/t.risk:0});
app.use(express.json({limit:'1mb'}));app.use(express.static(__dirname));
app.get('/api/health',(req,res)=>res.json({ok:true,service:'ai-trading-journal'}));
app.get('/api/trades',(req,res)=>{const rows=db.prepare('SELECT * FROM trades ORDER BY date DESC,id DESC').all();res.json(rows.map(calc))});
app.post('/api/trades',(req,res)=>{const {date,symbol,direction,setup,entry,exit,quantity,risk=0,emotion='',notes=''}=req.body;if(!date||!symbol||!direction||!setup||![entry,exit,quantity].every(Number.isFinite))return res.status(400).json({error:'Invalid trade data'});const info=db.prepare('INSERT INTO trades(date,symbol,direction,setup,entry,exit,quantity,risk,emotion,notes) VALUES(?,?,?,?,?,?,?,?,?,?)').run(date,String(symbol).toUpperCase(),direction,setup,entry,exit,quantity,risk,emotion,notes);res.status(201).json(calc(db.prepare('SELECT * FROM trades WHERE id=?').get(info.lastInsertRowid)))});
app.delete('/api/trades/:id',(req,res)=>{const r=db.prepare('DELETE FROM trades WHERE id=?').run(req.params.id);r.changes?res.status(204).end():res.status(404).json({error:'Trade not found'})});
app.delete('/api/trades',(req,res)=>{db.prepare('DELETE FROM trades').run();res.status(204).end()});
app.get('/api/analytics',(req,res)=>{const t=db.prepare('SELECT * FROM trades ORDER BY date ASC,id ASC').all().map(calc),p=t.map(x=>x.pnl),wins=p.filter(x=>x>0),losses=p.filter(x=>x<0),net=p.reduce((a,b)=>a+b,0),grossWin=wins.reduce((a,b)=>a+b,0),grossLoss=Math.abs(losses.reduce((a,b)=>a+b,0));const bySetup={};const byEmotion={};t.forEach(x=>{for(const [obj,key] of [[bySetup,x.setup],[byEmotion,x.emotion||'Unspecified']]){obj[key]??={trades:0,pnl:0,wins:0};obj[key].trades++;obj[key].pnl+=x.pnl;if(x.pnl>0)obj[key].wins++}});let equity=0;const curve=t.map(x=>(equity+=x.pnl,equity));res.json({totalTrades:t.length,netPnl:net,winRate:t.length?wins.length/t.length*100:0,profitFactor:grossLoss?grossWin/grossLoss:null,avgWin:wins.length?grossWin/wins.length:0,avgLoss:losses.length?grossLoss/losses.length:0,maxDrawdown:drawdown(curve),bySetup,byEmotion,equityCurve:curve})});
function drawdown(c){let peak=0,max=0;for(const v of c){peak=Math.max(peak,v);max=Math.max(max,peak-v)}return max}
app.post('/api/ai/review',async(req,res)=>{const trades=db.prepare('SELECT * FROM trades ORDER BY date DESC,id DESC LIMIT 100').all().map(calc);if(!trades.length)return res.status(400).json({error:'Add trades before requesting an AI review.'});if(!process.env.OPENAI_API_KEY)return res.json({source:'local',review:localReview(trades)});try{const client=new OpenAI({apiKey:process.env.OPENAI_API_KEY});const response=await client.responses.create({model:process.env.OPENAI_MODEL||'gpt-5-mini',input:`You are a disciplined trading journal coach. Analyze this JSON trade history. Do not predict markets or give buy/sell advice. Return concise sections: Performance, Behavioral Patterns, Risk Management, 3 Action Items. Mention uncertainty where data is small.\n${JSON.stringify(trades)}`});res.json({source:'openai',review:response.output_text})}catch(e){res.status(502).json({error:'AI service unavailable',fallback:localReview(trades)})}});
function localReview(t){const p=t.map(x=>x.pnl),w=p.filter(x=>x>0),l=p.filter(x=>x<0),net=p.reduce((a,b)=>a+b,0),wr=w.length/t.length*100,avgW=w.length?w.reduce((a,b)=>a+b,0)/w.length:0,avgL=l.length?Math.abs(l.reduce((a,b)=>a+b,0)/l.length):0,em={};t.forEach(x=>{em[x.emotion||'Unspecified']??={n:0,p:0};em[x.emotion||'Unspecified'].n++;em[x.emotion||'Unspecified'].p+=x.pnl});const best=Object.entries(em).sort((a,b)=>b[1].p-a[1].p)[0];const lines=[`Performance: ${t.length} trades, net P&L ₹${net.toFixed(2)}, win rate ${wr.toFixed(1)}%, average win ₹${avgW.toFixed(2)}, average loss ₹${avgL.toFixed(2)}.`];if(avgL>avgW&&avgW)lines.push('Risk Management: average losses exceed average wins; review stop placement and position sizing.');if(t.some(x=>['FOMO','Revenge','Greedy'].includes(x.emotion)))lines.push('Behavioral Patterns: emotional entries are present; review those trades separately.');if(best)lines.push(`Pattern: ${best[0]} has the strongest journal P&L contribution at ₹${best[1].p.toFixed(2)}.`);lines.push('Action Items: keep a pre-trade checklist; define risk before entry; review a consistent sample before changing strategy.');return lines.join('\n\n')}
app.listen(PORT,()=>console.log(`AI Trading Journal running on port ${PORT}`));